<table class="table">
  <thead>
    <tr>
      <?php foreach ($head as $item) : ?>
        <th scope="col"><?= $item; ?></th>
      <?php endforeach; ?>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($body as $item) : ?>
      <tr>
        <th scope="row"><?= $item['index']; ?></th>
        <td><?= $item['firstName']; ?></td>
        <td><?= $item['lastName']; ?></td>
        <td><?= $item['userName']; ?></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
