<div>
  <ul class="list-bullets">
    <li>Consectetur adipiscing elit</li>
    <li>Integer molestie lorem at massa</li>
    <li>Facilisis in pretium nisl aliquet</li>
  </ul>
</div>
<div>
  <table class="table table-finna-record record-details record-details-more">
    <tbody>
      <tr>
        <th>Description lists</th>
        <td>
          <div class="truncate-field truncate-done" data-rows="5">
            A description list if perfect for defining terms
          </div>
        </td>
      </tr>
      <tr>
        <th>Euismod</th>
        <td>
          <div class="truncate-field truncate-done" data-rows="5">
            Vestibulum lorem ex, feugiat id posuere nec, mattis vel metus.
            <br>
            Donec consequat auctor nunc, eget congue velit sagittis eget.

          </div>
        </td>
      </tr>
      <tr>
        <th>Malesuada porta</th>
        <td>
          <div class="truncate-field truncate-done" data-rows="5">
            Etiam ut diam faucibus, hendrerit sapien sed, fringilla leo.
          </div>
        </td>
      </tr>
      <tr>
        <th>Truncated term is a...</th>
        <td>
          <div class="truncate-field truncate-done" data-rows="5">
            Fusce sapien libero, ornare vitae interdum vitae, elementum eget enim. Duis commodo consectetur massa, sit amet lobortis felis feugiat ut.
          </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>
