<div class="container c-tooltip-container">
  <?= $this->render('components/01-molecules/05-tooltip/_tooltip.phtml', ['buttonClasses' => ['btn btn-primary'], 'position' => 'top', 'content' => '<h4>Tooltip top</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed convallis tempor suscipit. Mauris tellus enim, auctor et mi in, ultrices vehicula purus. Phasellus cursus velit et euismod pharetra.</p>', 'buttonText' => 'Show tooltip']) ?>
</div>
