<div class="container c-tooltip-container">
  <div class="tooltip fade right in" role="tooltip" id="tooltip275375" style="display: block;">
    <div class="tooltip-arrow"></div>
    <div class="tooltip-inner">
      <h4>Tooltip top</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed convallis tempor suscipit. Mauris tellus enim, auctor et mi in, ultrices vehicula purus. Phasellus cursus velit et euismod pharetra.</p>
    </div>
  </div>
</div>
