<?php $this->headScript()->appendFile('components/molecules/navigation/finna-multiselect/finna-multiselect.js'); ?>
<?php
  /**
   * Constructor for multiselect component.
   * 
   * Required data attributes are:
   * data-clear-text: Translation for clear button text.
   * data-label-id: Identifier for label, must be unique.
   * data-label-text: Translation for the label element.
   * data-label: Aria-label for the UL element.
   * data-placeholder: Placeholder text for search input.
   * data-entries: Array of objects.
   * data-name: Name for the select element.
   * use htmlspecialchars(json_encode($list), ENT_QUOTES, 'UTF-8'); to convert into
   * proper object in php
   * Objects must have the next values:
   * {
   *  displayText: Text to display for the option,
   *  value:       Option value.
   *  selected:    Should the option be selected when created.
   *  
   *  (optional):
   *  level: Used to create hierarchy.
   *  Level 0 is root. Level 1 is immediate child option. 
   *  Level 2 is child option for level 1 etc.
   * }
   */
  $entries = [
    ['displayText' => 'Demo1_level0', 'value' => 'demo1lvl0', 'selected' => false, 'level' => 0],
    ['displayText' => 'Demo2_level0', 'value' => 'demo1lvl1', 'selected' => false, 'level' => 0],
    ['displayText' => 'Demo3_level0', 'value' => 'demo1lvl2', 'selected' => false, 'level' => 0],
    ['displayText' => 'Demo4_level1', 'value' => 'demo1lvl3', 'selected' => false, 'level' => 1],
    ['displayText' => 'Demo5_level1', 'value' => 'demo1lvl4', 'selected' => false, 'level' => 1],
    ['displayText' => 'Demo6_level2', 'value' => 'demo1lvl5', 'selected' => false, 'level' => 2],
    ['displayText' => 'Demo7_level2', 'value' => 'demo2lvl0', 'selected' => true, 'level' => 0],
    ['displayText' => 'Demo8_level1', 'value' => 'demo1lvl7', 'selected' => false, 'level' => 1],
    ['displayText' => 'Demo9_level2', 'value' => 'demo1lvl8', 'selected' => false, 'level' => 0],
    ['displayText' => 'Demo10_level0', 'value' => 'demo1lvl9', 'selected' => false, 'level' => 0],
    ['displayText' => 'Demo11_level0', 'value' => 'demo1lvl10', 'selected' => false, 'level' => 0],
  ];
?>
<finna-multiselect
  data-entries="<?=htmlspecialchars(json_encode($entries), ENT_QUOTES, 'UTF-8')?>"
  data-clear-text="Empty selections."
  data-label-id="demo_select_label_id"
  data-label-text="Demo label text"
  data-label="Aria label for the ul element"
  data-placeholder="Search for"
  data-name="filter[]"
>

</finna-multiselect>