<?php
  $entries = [
    ['displayText' => 'Demo1_level0', 'value' => 'demo1lvl0', 'selected' => false, 'level' => 0],
    ['displayText' => 'Demo2_level0', 'value' => 'demo1lvl1', 'selected' => false, 'level' => 0],
    ['displayText' => 'Demo3_level1', 'value' => 'demo1lvl2', 'selected' => false, 'level' => 1],
    ['displayText' => 'Demo4_level2', 'value' => 'demo1lvl3', 'selected' => false, 'level' => 2],
    ['displayText' => 'Demo5_level3', 'value' => 'demo1lvl4', 'selected' => false, 'level' => 3],
    ['displayText' => 'Demo6_level2', 'value' => 'demo1lvl5', 'selected' => false, 'level' => 2],
    ['displayText' => 'Demo7_level0', 'value' => 'demo2lvl0', 'selected' => true, 'level' => 0],
    ['displayText' => 'Demo8_level1', 'value' => 'demo1lvl7', 'selected' => false, 'level' => 1],
    ['displayText' => 'Demo9_level2', 'value' => 'demo1lvl8', 'selected' => false, 'level' => 2],
    ['displayText' => 'Demo10_level1', 'value' => 'demo1lvl81', 'selected' => false, 'level' => 1],
    ['displayText' => 'Demo11_level2', 'value' => 'demo1lvl82', 'selected' => false, 'level' => 2],
    ['displayText' => 'Demo12_level0', 'value' => 'demo1lvl9', 'selected' => false, 'level' => 0],
    ['displayText' => 'Demo13_level0', 'value' => 'demo1lvl10', 'selected' => false, 'level' => 0],
    ['displayText' => 'Demo14_level0', 'value' => 'demo1lvl0', 'selected' => false, 'level' => 0],
    ['displayText' => 'Demo15_level0', 'value' => 'demo1lvl1', 'selected' => false, 'level' => 0],
    ['displayText' => 'Demo16_level1', 'value' => 'demo1lvl2', 'selected' => false, 'level' => 1],
    ['displayText' => 'Demo17_level2', 'value' => 'demo1lvl3', 'selected' => false, 'level' => 2],
    ['displayText' => 'Demo18_level3', 'value' => 'demo1lvl4', 'selected' => false, 'level' => 3],
    ['displayText' => 'Demo19_level2', 'value' => 'demo1lvl5', 'selected' => false, 'level' => 4],
    ['displayText' => 'Demo20_level0', 'value' => 'demo2lvl0', 'selected' => true, 'level' => 5],
    ['displayText' => 'Demo21_level1', 'value' => 'demo1lvl7', 'selected' => false, 'level' => 1],
    ['displayText' => 'Demo22_level2', 'value' => 'demo1lvl8', 'selected' => false, 'level' => 2],
    ['displayText' => 'Demo23_level1', 'value' => 'demo1lvl81', 'selected' => false, 'level' => 1],
    ['displayText' => 'Demo24_level2', 'value' => 'demo1lvl82', 'selected' => false, 'level' => 2],
    ['displayText' => 'Demo25_level0', 'value' => 'demo1lvl9', 'selected' => false, 'level' => 2],
    ['displayText' => 'Demo26_level0', 'value' => 'demo1lvl10', 'selected' => false, 'level' => 1],
  ];
?>
<finna-multiselect
  entries="<?=htmlspecialchars(json_encode($entries), ENT_QUOTES, 'UTF-8')?>"
  clear-text="Clear all selections"
  label-id="demo_select_label_id"
  label-text="Demo label text"
  description="Aria label for the ul element"
  placeholder="Search for"
  name="filter[]"
></finna-multiselect>
<?php $this->headScript()->appendFile('components/molecules/forms/finna-multiselect/finna-multiselect.js'); ?>
