<?php
  $entries = [
    ['displayText' => 'Demo1_level0', 'value' => 'demo1lvl0', 'selected' => false, 'level' => 0],
    ['displayText' => 'Demo2_level0', 'value' => 'demo1lvl1', 'selected' => false, 'level' => 0],
    ['displayText' => 'Demo3_level0', 'value' => 'demo1lvl2', 'selected' => false, 'level' => 1],
    ['displayText' => 'Demo4_level1', 'value' => 'demo1lvl3', 'selected' => false, 'level' => 2],
    ['displayText' => 'Demo5_level1', 'value' => 'demo1lvl4', 'selected' => false, 'level' => 3],
    ['displayText' => 'Demo6_level2', 'value' => 'demo1lvl5', 'selected' => false, 'level' => 2],
    ['displayText' => 'Demo7_level2', 'value' => 'demo2lvl0', 'selected' => true, 'level' => 0],
    ['displayText' => 'Demo8_level1', 'value' => 'demo1lvl7', 'selected' => false, 'level' => 1],
    ['displayText' => 'Demo9_level2', 'value' => 'demo1lvl8', 'selected' => false, 'level' => 0],
    ['displayText' => 'Demo10_level0', 'value' => 'demo1lvl9', 'selected' => false, 'level' => 0],
    ['displayText' => 'Demo11_level0', 'value' => 'demo1lvl10', 'selected' => false, 'level' => 0],
  ];
?>
<finna-multiselect
  entries="<?=htmlspecialchars(json_encode($entries), ENT_QUOTES, 'UTF-8')?>"
  clear-text="Clear all selections"
  label-id="demo_select_label_id"
  label-text="Demo label text"
  label="Aria label for the ul element"
  placeholder="Search for"
  name="filter[]"
></finna-multiselect>
<?php $this->headScript()->appendFile('components/molecules/forms/finna-multiselect/finna-multiselect.js'); ?>
