<div class="dropdown">
  <button href="#" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown">
    <span><?= $label; ?></span> <i class="fa fa-arrow-down"></i>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li role="menuitem">
      <a href=""><?= $item; ?></a>
    </li>
  </ul>
  <noscript><input type="submit" class="btn btn-default" value="<?= $submit; ?>" /></noscript>
</div>
