<div class="c-input-container">
  <div class="form-group">
    <?= $this->render('components/00-atoms/05-forms/_input.phtml', ['inputName' => $inputText, 'label' => $label, 'inputPlaceholder' => $inputPlaceholder, 'type' => 'text']) ?>
  </div>
  <div class="form-group has-error">
    <?= $this->render('components/00-atoms/05-forms/_input.phtml', ['inputName' => $inputInvalidText, 'label' => $label, 'inputPlaceholder' => $inputInvalidPlaceholder, 'required' => true, 'type' => 'text']) ?>
    <span class="help-block"><?= $inputError; ?></span>
  </div>
</div>
