<div class="c-input-container">
  <div class="form-group">
    <?= $this->render('components/00-atoms/05-forms/_textarea.phtml', ['inputName' => $textareaName, 'label' => $label, 'cols' => '10']) ?>
  </div>
  <div class="form-group has-error">
    <?= $this->render('components/00-atoms/05-forms/_textarea.phtml', ['inputName' => $textareaInvalidName, 'label' => $label, 'required' => true]) ?>
    <span class="help-block"><?= $inputError; ?></span>
  </div>
</div>
