<fieldset class="form-group">
  <legend class="hidden"><?= $inputRadioGroupLabel; ?></legend>
  <?php foreach ($inputRadioGroup as $index => $value) : ?>
    <div class="radio">
      <label for="<?= $inputName ?>-radio<?= $index + 1; ?>">
        <input type="radio" name="<?= $inputName ?>-radio" id="<?= $inputName ?>-radio<?= $index + 1; ?>" value="option<?= $index + 1; ?>" />
        <?= $value; ?>
      </label>
    </div>
  <?php endforeach; ?>
</fieldset>
