<div class="form-group checkbox">
  <label for="<?= $inputName; ?>-checkbox">
    <input type="checkbox" value="" name="<?= $inputName; ?>-checkbox" id="<?= $inputName; ?>-checkbox" /> Checkbox
  </label>
</div>
<div class="form-group checkbox">
  <label for="<?= $inputName; ?>-checkbox-invalid" style="color: #a94442;">
    <input type="checkbox" value="" name="<?= $inputName; ?>-checkbox-invalid" id="<?= $inputName; ?>-checkbox-invalid" required aria-required="true" /> Checkbox
  </label>
  <div style="color: #a94442; margin-top: 0.5rem;">
    <?= $inputError; ?>
  </div>
</div>
