<div class="c-input-container">
  <div class="form-group">
    <?= $this->render('components/00-atoms/05-forms/_input-styled.phtml', ['inputName' => $inputLargeText, 'label' => $label, 'placeholder' => $inputLargePlaceholder, 'type' => 'text', 'inputClass' => 'input-group-lg']) ?>
  </div>
  <div class="form-group">
    <?= $this->render('components/00-atoms/05-forms/_input-styled.phtml', ['inputName' => $inputText, 'label' => $label, 'placeholder' => $inputPlaceholder, 'type' => 'text']) ?>
  </div>
  <div class="form-group">
    <?= $this->render('components/00-atoms/05-forms/_input-styled.phtml', ['inputName' => $inputSmallText, 'label' => $label, 'placeholder' => $inputSmallPlaceholder, 'type' => 'text', 'inputClass' => 'input-group-sm']) ?>
  </div>
</div>
