<div class="form-group">
  <label for="<?= $inputName ?>-text-large"><?= $label; ?></label>
  <div class="input-group input-group-lg">
    <input id="<?= $inputName ?>-text-large>" name="<?= $inputName ?>-text-large" class="form-control" type="text" placeholder=".input-group-lg">
  </div>
</div>
<div class="form-group">
  <label for="<?= $inputName ?>-text-default"><?= $label; ?></label>
  <div class="input-group">
    <input id="<?= $inputName ?>-text-default" name="<?= $inputName ?>-text-default" class="form-control" type="text" placeholder="Default input">
  </div>
</div>
<div class="form-group">
  <label for="<?= $inputName ?>-text-small"><?= $label; ?></label>
  <div class="input-group input-group-sm">
    <input id="<?= $inputName ?>-text-small" name="<?= $inputName ?>-text-small" class="form-control" type="text" placeholder=".input-group-sm">
  </div>
</div>
