<div class="c-input-container">
  <div class="form-group has-success has-feedback">

    <?= $this->render('components/00-atoms/05-forms/_input.phtml', ['inputName' => $inputTextSuccess, 'label' => $label, 'labelClass' => 'control-label', 'inputPlaceholder' => $inputPlaceholder, 'type' => 'text']) ?>

    <span class="fa fa-check form-control-feedback"></span>
  </div>
  <div class="form-group has-warning has-feedback">

    <?= $this->render('components/00-atoms/05-forms/_input.phtml', ['inputName' => $inputTextWarning, 'label' => $label, 'labelClass' => 'control-label', 'inputPlaceholder' => $inputPlaceholder, 'type' => 'text']) ?>

    <span class="fa fa-exclamation-triangle form-control-feedback"></span>
  </div>
  <div class="form-group has-error has-feedback">

    <?= $this->render('components/00-atoms/05-forms/_input.phtml', ['inputName' => $inputTextError, 'label' => $label, 'labelClass' => 'control-label', 'inputPlaceholder' => $inputPlaceholder, 'type' => 'text']) ?>

    <span class="fa fa-times form-control-feedback"></span>
  </div>
  <div class="form-group checkbox has-success">
    <label for="<?= $inputName; ?>-checkbox-success" s>
      <input type="checkbox" value="" name="<?= $inputName; ?>-checkbox-success" id="<?= $inputName; ?>-checkbox-success" required aria-required="true" /> Checkbox
    </label>
  </div>
  <div class="form-group checkbox has-warning">
    <label for="<?= $inputName; ?>-checkbox-warning" s>
      <input type="checkbox" value="" name="<?= $inputName; ?>-checkbox-warning" id="<?= $inputName; ?>-checkbox-warning" required aria-required="true" /> Checkbox
    </label>
  </div>
  <div class="form-group checkbox has-error">
    <label for="<?= $inputName; ?>-checkbox-invalid" s>
      <input type="checkbox" value="" name="<?= $inputName; ?>-checkbox-invalid" id="<?= $inputName; ?>-checkbox-invalid" required aria-required="true" /> Checkbox
    </label>
  </div>
</div>
