<div class="form-group has-success">
  <label for="<?= $inputName ?>-text" class="control-label"><?= $label; ?></label>
  <input class="form-control" id="<?= $inputName ?>-text" name="<?= $inputName ?>-text" placeholder="<?= $inputPlaceholder ?>" aria-placeholder="<?= $inputPlaceholder ?>" type="text" />
</div>
<div class="form-group has-warning">
  <label for="<?= $inputName ?>-text" class="control-label"><?= $label; ?></label>
  <input class="form-control" id="<?= $inputName ?>-text" name="<?= $inputName ?>-text" placeholder="<?= $inputPlaceholder ?>" aria-placeholder="<?= $inputPlaceholder ?>" type="text" />
</div>
<div class="form-group has-error">
  <label for="<?= $inputName ?>-text" class="control-label"><?= $label; ?></label>
  <input class="form-control" id="<?= $inputName ?>-text" name="<?= $inputName ?>-text" placeholder="<?= $inputPlaceholder ?>" aria-placeholder="<?= $inputPlaceholder ?>" type="text" />
</div>
<div class="form-group checkbox has-success">
  <label for="<?= $inputName; ?>-checkbox-invalid">
    <input type="checkbox" value="" name="<?= $inputName; ?>-checkbox-invalid" id="<?= $inputName; ?>-checkbox-invalid" required aria-required="true" /> Checkbox
  </label>
</div>
<div class="form-group checkbox has-warning">
  <label for="<?= $inputName; ?>-checkbox-invalid">
    <input type="checkbox" value="" name="<?= $inputName; ?>-checkbox-invalid" id="<?= $inputName; ?>-checkbox-invalid" required aria-required="true" /> Checkbox
  </label>
</div>
<div class="form-group checkbox has-error">
  <label for="<?= $inputName; ?>-checkbox-invalid">
    <input type="checkbox" value="" name="<?= $inputName; ?>-checkbox-invalid" id="<?= $inputName; ?>-checkbox-invalid" required aria-required="true" /> Checkbox
  </label>
</div>
